#!/usr/bin/env bash

netstat -w1 2>/dev/null | awk '
    /^[[:space:]]*[0-9]/ {
        sample_count += 1
        if (sample_count >= 2) {
            print $3 "@" $6
            exit
        }
    }
'
