#!/usr/bin/env bash

PERCENTAGE=$(pmset -g batt | grep -Eo '[0-9]+%' | head -n 1 | tr -d '%')
SOURCE=$(pmset -g batt | sed -n "s/.*'\([^']*\)'.*/\1/p" | head -n 1)

printf '{"percentage":"%s","source":"%s"}\n' "$PERCENTAGE" "$SOURCE"
